// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtkeijniuexghrlrbyhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0a2Vpam5pdWV4Z2hybHJieWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjMyNTksImV4cCI6MjA2Mzg5OTI1OX0.wMi1_K5bftGmW4zJitNboz6F_7Ri_mQTIx6UZQ7yun8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);